# Generated by Django 6.0 on 2025-12-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='customer_data',
            field=models.JSONField(default=dict, help_text='Fields list that customer should fill theme before purchase', verbose_name='Required information'),
        ),
    ]
