# Generated by Django 6.0 on 2025-12-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderitem_customer_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer_data',
        ),
        migrations.RemoveField(
            model_name='service',
            name='required_fields',
        ),
    ]
